### ISSUE TITLE
Only post inbound Mobile Commons messages to Conversations API

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/blink#109]
Refs #102, https://dosomething.slack.com/archives/C2C8NLNAY/p1503003860000137

The Conversations API could be responsible for determining if a `/receive-message` payload is inbound or outbound, but ideally the `gambit-message-data-relay` should only make a Conversation API request for a Twilio message when the From is not equal to our Twilio number (for staging its +14069981855).

**Comment by sergii-tkachenko** [comment]
@aaronschachter To clarify how the filter works. Blink should send only messages with `"SmsStatus": "received",`, correct?
cc @rapala61

**Comment by rapala61** [comment]
@sergii-tkachenko AFAIK yes, outgoing would be `sent` I believe.

**Comment by aaronschachter** [comment]
I'm not sure about which `smsStatus` value to filter by -- I was thinking we'd exclude any messages where the message `From` is set to whatever the Conversations `TWILIO_FROM_NUMBER` is set to.

**Comment by sergii-tkachenko** [comment]
Per chat with @aaronschachter over a slack call, we're going to use `smsStatus` attribute to determine whether a message is inbound. However, since this field is not in Twilio docs, I'll reach out to Kevin to ensure field's persistence over different message types.
