### ISSUE TITLE
Unexpected validation error in v1.5.0 release

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/blink#142]
> at=warning application=blink env=production code=error_validation_failed request_id=370f9f55-5ded-486e-bcf7-b4f9d9b0d8a5 method=POST host=blink.dosomething.org path=/api/v1/events/user-create fwd=52.1.10.35 protocol=https MessageValidationBlinkError: child "addr_city" fails because ["addr_city" must be a string]

cc @DFurnes 

May be related to #129 or #133.

**Comment by DFurnes** [comment]
How often are you receiving this error? Curious if it's one "bad" record, or a wider issue.

**Comment by sergii-tkachenko** [comment]
I saw 4 instances of this on Prod, but many more during the Staging backfill.

**Comment by sergii-tkachenko** [comment]
Just checked Prod again, 12 instances since yesterday.

**Comment by DFurnes** [comment]
Just gave a look and I believe this should not be a big issue. There are 3,618 records (out of 9.3M) where `addr_city` is not a string. Of those, 3,146 just explicitly store `null` (which shouldn't cause any issues). The remaining 472 have awkward-looking objects, like this:

```
addr_city: { "value" : "NY" }
```

These are probably from an early attempt at Phoenix migration & we can write a script to clean 'em up.

**Comment by sergii-tkachenko** [comment]
What concerns me more is that active users are affected by this. I'd like to check what those 12 members from yesterday are.

**Comment by sergii-tkachenko** [comment]
Haven't seen these errors on prod anymore. One thing I still want to make sure of is whether `null` value is processed correctly.

**Comment by sergii-tkachenko** [comment]
Ok, nulls look fine.

**Comment by sergii-tkachenko** [comment]
Empty fields too. I think we can close this in Blink. @DFurnes Do you think it would make sense to fix corrupt values that look like objects?

**Comment by DFurnes** [comment]
Yep, I'll make a backlog ticket for Rocket.
