### ISSUE TITLE
Workers crash when they can't fit all messages in the queue to the memory

### ISSUE THREAD

**Issue by sergii-tkachenko** [DoSomething/blink#154]
Blink wasn't designed with support for queues with lengthy backlogs.
Given the asynchronous nature of Node.js, workers are trying to consume all available messages from their queues. When queue backlog has more messages than possible to fit into the memory available to a worker, worker crashes.

![image](https://user-images.githubusercontent.com/672669/31727239-159e8c80-b3f7-11e7-9199-9a06891c8ecd.png)

This is important for two reasons:

- Longer backlogs are anticipated in Blink with rate limiter in place
- Expected backfill operations in most cases would generate queue backlogs longer than normal relay operations would do. For example, customer.io backfill on the screenshot above produced 70K messages in the queue and `customer-io-update-customer` couldn't fit all them into its memory.

**Comment by sergii-tkachenko** [comment]
There are few approaches to solve this problem, but they all are centered around the same idea: *limit number of messages worker consumes at a time*.

1) Keep count of consumed messages per queue, stop consuming when the limit is reached. Continue when messages are processed.
To investigate if it's technically possible and if this would mean stopping AMQP channel.

2) Solve #70 and use RabbitMQ's prefetch count instead.

**Comment by rapala61** [comment]
This is an interesting issue. I'm not a seasoned RabbitMQ dev, but I thought of an abstract idea. In combination with solving #70.
>let me know if it doesn't work!
- Let's create a retry queue and retry worker. Messages that go into this retry queue would have to know where they should be retried to, etc.
- In our workers, keep count of how many times requests are retried (we are already), then send to retry queue after say 5 retries.
- Let's keep exponentially backing off retries on this retry queue until it reaches a point we have to send it to a deadLetter queue. I'm not sure what this threshold would be.

**Comment by sergii-tkachenko** [comment]
@rapala61 Thanks for the suggestion. You can check out #70, I listed possible solutions there. Creating retry queue is exactly what would be the ideal solution to this problem. There's a way to make it work without retry worker using dead letter exchange and message expiration. See https://github.com/DoSomething/blink/issues/70#issuecomment-337695471 item 2.

**Comment by sergii-tkachenko** [comment]
@rapala61 Thanks for the suggestion! I think you got a good grasp on this problem!

Creating retry queue is exactly what would be the ideal solution to this problem. There's a way to make it work without retry worker using dead letter exchange and message expiration. See https://github.com/DoSomething/blink/issues/70#issuecomment-337695471 item 2.

**Comment by rapala61** [comment]
I read #70 known approach 1, which talks about dead letter exchange. 

What is the advantage of using a dead letter exchange vs having a retry worker with prefetch? I think it would be simpler to sort of relegate retries to that queue/worker. The retry worker would not suffer from the same memory problem because, as I understand, if it uses prefetch, it wouldn't hold all messages in memory. Again, doing my best with what little I know about these complexities.

**Comment by sergii-tkachenko** [comment]
- Dead letter exchange approach automatically solves logistic for message redelivery
- Each queue will have its own retry queue, which makes debugging and monitoring more simple and explicit
- We'd need to make logical exceptions for the retry worker in code, which will code more complex and less unified
- We won't need to maintain and pay for one extra worker

**Comment by rapala61** [comment]
Thats a lot of advantages! Just throwing my 0.2 cents out there. You got this!

**Comment by sergii-tkachenko** [comment]
Update on approach 1 of this issue. It's technically impossible to "pause" a consumer without actually canceling it. Canceling the consumer is just not an option for us, as it detaches messages in Blink's memory from their counterparts in RabbitMQ, so Blink worker won't be able to `ack` or `nack` them.

**Comment by sergii-tkachenko** [comment]
This leaves us with approach 2: solve #70 and use `prefetch count`. And the only viable option to fix this would be to introduce "retry queues", see https://github.com/DoSomething/blink/issues/70#issuecomment-337990929.

**Comment by sergii-tkachenko** [comment]
Heh. Before implementing the dead letters approach, I discovered that it may be not viable too.
https://jack-vanlightly.com/blog/2017/3/24/rabbitmq-delayed-retry-approaches-that-work

> Messages are only removed from the head of the queue. You cannot use a single wait queue for any back-off strategy. If you have a message with a TTL of 10 minutes at the head of the queue and a message with a TTL of 1 minute behind it, the second message will wait for ten minutes.
