### ISSUE TITLE
parseMessageIdFromBody(): Non empty array expected in response

### ISSUE THREAD

**Issue by rapala61** [DoSomething/blink#203]
## Current Behavior
Blink throws an exception when retrieving a message by `MessageSid` (platformMessageId) and the response is an empty array.

## Expected Behavior
G-Conversations should always return a message when Blink requests it using the `MessageSid` Twilio sends to the `/api/v1/webhooks/twilio-sms-outbound-status` endpoint.

## Why This Matters
It's an unrecoverable error that gets retried for 24hr. Polluting our logs and alerts.

## Notes

- I'm starting this issue here in Blink. If we decide that Blink's behavior should remain this way. The fix would be implemented in G-Conversations.

- If Twilio is sending us an status update it's certain that this message should exist in our DB -- Since we save the `platformMessageId` that Twilio responds with after the message is sent in G-Conversations. **Are we failing to record the `platformMessageId` in some edge-cases?**

- Should Blink throw an exception in this case. I still think it should. This is the reason we are detecting an unexpected response from G-Conversations. I think we should keep it that way. What do you think?
 @aaronschachter

**Comment by aaronschachter** [comment]
> Should Blink throw an exception in this case. I still think it should. This is the reason we are detecting an unexpected response from G-Conversations. I think we should keep it that way

Sounds right to me too!

**Comment by rapala61** [comment]
April 30th is the first time this error happened in Blink.

**Comment by rapala61** [comment]
That date lines up perfectly with release [2.5.7](https://github.com/DoSomething/gambit-conversations/releases/tag/2.5.7). It certainly looks suspicious since the change I made does impact the function that sends outbound messages to Twilio, ugh!

**Comment by rapala61** [comment]
Closing this issue since it's looking like the fix will be in G-Conversations: https://github.com/DoSomething/gambit-conversations/issues/331.
